# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stalewood < Formula
  desc "Find and reap merged git worktrees"
  homepage "https://github.com/retif/stalewood"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/retif/stalewood/releases/download/v0.1.6/stalewood_0.1.6_darwin_amd64.tar.gz"
      sha256 "15fc69b133ee30deb7706e97ba8ab0de6de83b2c25b094266947dcaab3a8b781"

      define_method(:install) do
        bin.install "stalewood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/retif/stalewood/releases/download/v0.1.6/stalewood_0.1.6_darwin_arm64.tar.gz"
      sha256 "b32ac15df6f6a1064aaad6f0148a38619869b3eebcf6e056c1219d5cce0c2229"

      define_method(:install) do
        bin.install "stalewood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/retif/stalewood/releases/download/v0.1.6/stalewood_0.1.6_linux_amd64.tar.gz"
      sha256 "43cc91f72eb92bc4da994e2e08e20599c943db84a9ecd1b5f1b499d233dc44c3"
      define_method(:install) do
        bin.install "stalewood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/retif/stalewood/releases/download/v0.1.6/stalewood_0.1.6_linux_arm64.tar.gz"
      sha256 "2b066526314a7e10412e765d5558ae56cb82a500946c1c7b8514fe85ac6ccbcc"
      define_method(:install) do
        bin.install "stalewood"
      end
    end
  end

  test do
    system "#{bin}/stalewood", "--version"
  end
end
