# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stalewood < Formula
  desc "Find and reap merged git worktrees"
  homepage "https://github.com/retif/stalewood"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/retif/stalewood/releases/download/v0.1.3/stalewood_0.1.3_darwin_amd64.tar.gz"
      sha256 "82ccdba4596a94a8ecdf375b6145d0fe5a90db582023ece38f66b110180e77d5"

      define_method(:install) do
        bin.install "stalewood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/retif/stalewood/releases/download/v0.1.3/stalewood_0.1.3_darwin_arm64.tar.gz"
      sha256 "90fda4dcaf12207f8e175395ba2303a9b0efb61346b4c4fb5f76846da06764bb"

      define_method(:install) do
        bin.install "stalewood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/retif/stalewood/releases/download/v0.1.3/stalewood_0.1.3_linux_amd64.tar.gz"
      sha256 "15a3502e2473aaa4417874f5a76ed752394ad0fcdd8fcd1478cb18c51df9d522"
      define_method(:install) do
        bin.install "stalewood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/retif/stalewood/releases/download/v0.1.3/stalewood_0.1.3_linux_arm64.tar.gz"
      sha256 "31108a96918c5c78c5ad1a2a0c95f0d9ff2e6a8aae095d1b8b86547a565a883b"
      define_method(:install) do
        bin.install "stalewood"
      end
    end
  end

  test do
    system "#{bin}/stalewood", "--version"
  end
end
